RailsProject/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages
  resources :battlegrounds, only: %i[index show]
  resources :players, only: %i[index show]
  resources :teams, only: %i[index show]

  get 'search_results', to: 'search#results', as: 'search_results'

  get 'static/:permalink', to: 'pages#static', as: 'static'

  root to: 'battlegrounds#index'
end

RailsProject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RailsProject/app/models/battleground.rb
# frozen_string_literal: true

class Battleground < ApplicationRecord
  has_many :teams
  has_many :players

  validates :name, :location, presence: true
end

RailsProject/app/models/page.rb
class Page < ApplicationRecord
end

RailsProject/app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  belongs_to :battleground
  belongs_to :team

  validates :name, :specialty, presence: true
end

RailsProject/app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  belongs_to :battleground
  has_many :players

  validates :name, :quote, presence: true
end

RailsProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RailsProject/app/controllers/battlegrounds_controller.rb
# frozen_string_literal: true

class BattlegroundsController < ApplicationController
  def index
    @battlegrounds = Battleground.all
  end

  def show
    @battleground = Battleground.includes(:teams).find(params[:id])
  end
end

RailsProject/app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  http_basic_authenticate_with name: 'missy', password: 'Password01'
  before_action :set_page, only: %i[show edit update destroy]

  def static
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show; end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

RailsProject/app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  def index
    @players = Player.includes(:battleground).page(params[:page]).per(10)
  end

  def show
    @player = Player.includes(:battleground, :team).find(params[:id])
  end
end

RailsProject/app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def results
    @query = params[:q]
    @battleground = Battleground.where('name LIKE ?', "%#{@query}%")
    @team = Team.includes(:battleground).where('name LIKE ?', "%#{@query}%")
    @player = Player.includes(:battleground, :team).where('name LIKE ?', "%#{@query}%")

    @search_option = params[:search_option]

    if @query == ''
      @search_query = []
    else
      case @search_option
      when 'Search All'
        @search_query = @battleground + @team + @player
      when 'Battleground'
        @search_query = @battleground
      when 'Team'
        @search_query = @team
      when 'Player'
        @search_query = @player
      end
    end
  end
  end

RailsProject/app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  def index
    @teams = Team.includes(:battleground).page(params[:page]).per(10)
  end

  def show
    @team = Team.includes(:battleground).find(params[:id])
  end
end

RailsProject/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsProject/app/helpers/battlegrounds_helper.rb
module BattlegroundsHelper
end

RailsProject/app/helpers/pages_helper.rb
module PagesHelper
end

RailsProject/app/helpers/players_helper.rb
module PlayersHelper
end

RailsProject/app/helpers/search_helper.rb
module SearchHelper
end

RailsProject/app/helpers/teams_helper.rb
module TeamsHelper
end

RailsProject/app/views/battlegrounds/index.html.erb
<h2 class="title is-3">Battlegrounds</h2>
<hr/>
        <% @battlegrounds.each do |battleground| %>
        <h2 class="title is-4"><%= link_to battleground.name, battleground %></h2>
        <h3 class="subtitle is-6 is-spaced">Location: <%= battleground.location %></h3>
        <% end %>

RailsProject/app/views/battlegrounds/show.html.erb
<h2 class="title is-size-3"><%= @battleground.name %></h2>
<h3 class="subtitle is-size-6"><%= @battleground.class.name %></h3>
<hr/>

  <h3 class= "subtitle is-size-5"><strong>Current Top Teams:</strong></h3>

    <ol>
      <% @battleground.teams.each do |team| %>
        <li class="title is-size-5 is-spaced"><%= link_to team.name, team %></li>
        <h4 class="subtitle is-size-6">Players:</h4>
              <ul class="subtitle is-size-6 is-spaced">
                <% team.players.each do |player| %>
                <h4><%= link_to player.name, player %></h4>
              <% end %>
              </ul>
      <% end %>
    </ol>

<p><%= link_to 'Back', battlegrounds_path %></p>

RailsProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
    <section class="section is hero is-small is-dark is-bold">
      <div class="container">
        <h1 class="title is-2">Magic Realm Tournament</h1>
          <nav class= "navbar" aria-label="main navigation">
            <div id="navbarBasicExample" class="navbar-menu">
              <div class="navbar-start">
                <%= link_to 'Home', root_path, :class=>"navbar-item" %>
                <%= link_to 'Teams', teams_path, :class=>"navbar-item" %>
                <%= link_to 'Players', players_path, :class=>"navbar-item" %>
                <%= link_to 'About', static_path(permalink: 'about-us'), :class=>"navbar-item" %>
              </div>
            </div>

           <%= form_tag(search_results_path, method: "get") do %>
              <div class="navbar-item field has-addons">
                <div class="control select">
                  <%= select_tag "search_option", "<option>Search All</option><option>Battleground</option><option>Team</option><option>Player</option>".html_safe %>
                </div>
                <div class="control">
                  <%= text_field_tag(:q, nil, class: "input") %>
                </div>
                <div class="control">
                  <%= submit_tag("Search", class: "button is-info") %>
                </div>
              </div>
            <% end %>
          </nav>
        </div>
    </section>

    <div class="container">
      <section class= "section">
        <%= yield %>
      </section>
    </div>
  </body>
</html>

RailsProject/app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RailsProject/app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

RailsProject/app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

RailsProject/app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

RailsProject/app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

RailsProject/app/views/pages/static.html.erb
<h2 class="title is-3 is-spaced"><%= @page.title%></h2>
<hr/>
<p><%= @page.content %></p>

RailsProject/app/views/players/index.html.erb
<h2 class="title is-3">All Players</h2>
  <hr />
  <% @players.each do |player| %>
    <h3 class="title is-5"><%= link_to player.name, player %></h3>
    <h3 class="subtitle is-6 is-spaced"><%= player.specialty %></h3>
  <% end %>
  <hr />

  <div class="columns is-centered">
    <%= paginate @players %></div>
    <br />
    <%= page_entries_info @players %>

RailsProject/app/views/players/show.html.erb
<h2 class="title is-3 is-spaced ">Player</h2>
<hr/>
<h4 class="title is-5"><%= @player.name %> of <%= @player.team.name %></h4>
<h4 class="subtitle is-6">Specialty: <%= @player.specialty %></h4>

RailsProject/app/views/search/results.html.erb
  <div class="container">
    <h1 class="title is-3 is-spaced">Search Results</h1>
        <h3 class= "subtitle is-6">Results found for "<%= @query %>" returned <%= pluralize(@search_query.size, 'result')%>.</h3>
    </div>

<div class="container">
  <section class="section">
        <% @search_query.each do |s|%>
          <h1 class="title is-size-5"><%= link_to s.name, s %></h1>
          <h2 class="subtitle is-size-6 is-spaced">
          <%= s.class.name %>
          </h2>
          <% end %>
    </section>
</div>